language: java
sudo: false
before_install:
  - chmod +x mvnw
script: 
  - mvn clean install
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    on_success: always
  email:
  on_failure: always
  on_success: always
